
2018-10-26 08:54:21
[INFO]-[Thread: main]-[org.eclipse.jetty.server.Server.doStart()]: jetty-8.1.8.v20121106

2018-10-26 08:54:22
[INFO]-[Thread: main]-[org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitServlet()]: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

2018-10-26 08:54:22
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 08:54:22
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 08:54:22
[WARN]-[Thread: main]-[net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded()]: diskStorePath 'C:\Users\ADMINI~1\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created203367515449124584diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.

2018-10-26 08:54:22
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created203367515449124584diskstore\user%0049d_token.data

2018-10-26 08:54:22
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created203367515449124584diskstore\token_user%0049d.data

2018-10-26 08:54:22
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created203367515449124584diskstore\token_time.data

2018-10-26 08:54:22
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-1} inited

2018-10-26 08:54:35
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-2} inited

2018-10-26 08:54:35
[INFO]-[Thread: main]-[org.eclipse.jetty.server.AbstractConnector.doStart()]: Started SelectChannelConnector@0.0.0.0:8082

2018-10-26 09:39:55
[WARN]-[Thread: qtp1684792003-29]-[org.eclipse.jetty.http.HttpGenerator.addContent()]: Ignoring extra content {}

2018-10-26 09:39:55
[INFO]-[Thread: qtp1684792003-27]-[com.xxl.sso.core.util.JedisUtil.getInstance()]: >>>>>>>>>>> xxl-sso, JedisUtil.ShardedJedisPool init success.

2018-10-26 10:06:16
[INFO]-[Thread: main]-[org.eclipse.jetty.server.Server.doStart()]: jetty-8.1.8.v20121106

2018-10-26 10:06:16
[INFO]-[Thread: main]-[org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitServlet()]: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

2018-10-26 10:06:16
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:06:16
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:06:16
[WARN]-[Thread: main]-[net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded()]: diskStorePath 'C:\Users\ADMINI~1\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created8755250497824556176diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.

2018-10-26 10:06:16
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created8755250497824556176diskstore\user%0049d_token.data

2018-10-26 10:06:16
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created8755250497824556176diskstore\token_user%0049d.data

2018-10-26 10:06:16
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created8755250497824556176diskstore\token_time.data

2018-10-26 10:06:17
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-1} inited

2018-10-26 10:06:29
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-2} inited

2018-10-26 10:06:29
[INFO]-[Thread: main]-[org.eclipse.jetty.server.AbstractConnector.doStart()]: Started SelectChannelConnector@0.0.0.0:8082

2018-10-26 10:06:34
[INFO]-[Thread: qtp1684792003-29]-[com.xxl.sso.core.util.JedisUtil.getInstance()]: >>>>>>>>>>> xxl-sso, JedisUtil.ShardedJedisPool init success.

2018-10-26 10:13:26
[INFO]-[Thread: main]-[org.eclipse.jetty.server.Server.doStart()]: jetty-8.1.8.v20121106

2018-10-26 10:13:26
[INFO]-[Thread: main]-[org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitServlet()]: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

2018-10-26 10:13:26
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:13:26
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:13:26
[WARN]-[Thread: main]-[net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded()]: diskStorePath 'C:\Users\ADMINI~1\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created2915449899020074240diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.

2018-10-26 10:13:26
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created2915449899020074240diskstore\user%0049d_token.data

2018-10-26 10:13:26
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created2915449899020074240diskstore\token_user%0049d.data

2018-10-26 10:13:26
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created2915449899020074240diskstore\token_time.data

2018-10-26 10:13:27
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-1} inited

2018-10-26 10:13:36
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-2} inited

2018-10-26 10:13:36
[INFO]-[Thread: main]-[org.eclipse.jetty.server.AbstractConnector.doStart()]: Started SelectChannelConnector@0.0.0.0:8082

2018-10-26 10:13:41
[INFO]-[Thread: qtp1684792003-28]-[com.xxl.sso.core.util.JedisUtil.getInstance()]: >>>>>>>>>>> xxl-sso, JedisUtil.ShardedJedisPool init success.

2018-10-26 10:18:21
[ERROR]-[Thread: qtp1684792003-27]-[com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.logWrite()]: 
---Exception Log Begin---
Controller:com.ht.fault.order.ManageController
Method:faultPie
Exception Type:com.jfinal.plugin.activerecord.ActiveRecordException
Exception Details:
com.jfinal.plugin.activerecord.ActiveRecordException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values, f.`type` names  from ht_im_order_take t JOIN ht_im_fault_form f ON t.fau' at line 1
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:336)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:347)
	at com.jfinal.plugin.activerecord.Db.find(Db.java:271)
	at com.ht.fault.order.ManageService.groupType(ManageService.java:270)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.CGLIB$groupType$12(<generated>)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d$$FastClassByCGLIB$$16354604.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:82)
	at com.jfinal.aop.Callback.intercept(Callback.java:96)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.groupType(<generated>)
	at com.ht.fault.order.ManageController.faultPie(ManageController.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.intercept(ExceptionIntoLogInterceptor.java:21)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.SSOInterceptor.intercept(SSOInterceptor.java:73)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.BaseInterceptor.intercept(BaseInterceptor.java:16)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values, f.`type` names  from ht_im_order_take t JOIN ht_im_fault_form f ON t.fau' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2683)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2144)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2310)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:321)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:334)
	... 47 more

2018-10-26 10:18:21
[ERROR]-[Thread: qtp1684792003-27]-[com.jfinal.core.ActionHandler.handle()]: /manage/faultPie
com.jfinal.render.RenderException: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:63)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:99)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.template.source.FileSource.getContent(FileSource.java:70)
	at com.jfinal.template.Engine.buildTemplateBySourceFactory(Engine.java:153)
	at com.jfinal.template.Engine.getTemplate(Engine.java:138)
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:60)
	... 26 more

2018-10-26 10:18:32
[ERROR]-[Thread: qtp1684792003-31]-[com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.logWrite()]: 
---Exception Log Begin---
Controller:com.ht.fault.order.ManageController
Method:faultPie
Exception Type:com.jfinal.plugin.activerecord.ActiveRecordException
Exception Details:
com.jfinal.plugin.activerecord.ActiveRecordException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values, f.`type` names  from ht_im_order_take t JOIN ht_im_fault_form f ON t.fau' at line 1
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:336)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:347)
	at com.jfinal.plugin.activerecord.Db.find(Db.java:271)
	at com.ht.fault.order.ManageService.groupType(ManageService.java:270)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.CGLIB$groupType$12(<generated>)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d$$FastClassByCGLIB$$16354604.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:82)
	at com.jfinal.aop.Callback.intercept(Callback.java:96)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.groupType(<generated>)
	at com.ht.fault.order.ManageController.faultPie(ManageController.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.intercept(ExceptionIntoLogInterceptor.java:21)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.SSOInterceptor.intercept(SSOInterceptor.java:73)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.BaseInterceptor.intercept(BaseInterceptor.java:16)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values, f.`type` names  from ht_im_order_take t JOIN ht_im_fault_form f ON t.fau' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2683)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2144)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2310)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:321)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:334)
	... 47 more

2018-10-26 10:18:32
[ERROR]-[Thread: qtp1684792003-31]-[com.jfinal.core.ActionHandler.handle()]: /manage/faultPie
com.jfinal.render.RenderException: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:63)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:99)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.template.source.FileSource.getContent(FileSource.java:70)
	at com.jfinal.template.Engine.buildTemplateBySourceFactory(Engine.java:153)
	at com.jfinal.template.Engine.getTemplate(Engine.java:138)
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:60)
	... 26 more

2018-10-26 10:19:12
[INFO]-[Thread: main]-[org.eclipse.jetty.server.Server.doStart()]: jetty-8.1.8.v20121106

2018-10-26 10:19:12
[INFO]-[Thread: main]-[org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitServlet()]: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

2018-10-26 10:19:12
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:19:12
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:19:12
[WARN]-[Thread: main]-[net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded()]: diskStorePath 'C:\Users\ADMINI~1\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created7756856842696056817diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.

2018-10-26 10:19:12
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created7756856842696056817diskstore\user%0049d_token.data

2018-10-26 10:19:12
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created7756856842696056817diskstore\token_user%0049d.data

2018-10-26 10:19:12
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created7756856842696056817diskstore\token_time.data

2018-10-26 10:19:12
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-1} inited

2018-10-26 10:19:26
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-2} inited

2018-10-26 10:19:26
[INFO]-[Thread: main]-[org.eclipse.jetty.server.AbstractConnector.doStart()]: Started SelectChannelConnector@0.0.0.0:8082

2018-10-26 10:19:30
[INFO]-[Thread: qtp1684792003-27]-[com.xxl.sso.core.util.JedisUtil.getInstance()]: >>>>>>>>>>> xxl-sso, JedisUtil.ShardedJedisPool init success.

2018-10-26 10:19:50
[ERROR]-[Thread: qtp1684792003-30]-[com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.logWrite()]: 
---Exception Log Begin---
Controller:com.ht.fault.order.ManageController
Method:faultPie
Exception Type:com.jfinal.plugin.activerecord.ActiveRecordException
Exception Details:
com.jfinal.plugin.activerecord.ActiveRecordException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values, f.`type` names  from ht_im_order_take t JOIN ht_im_fault_form f ON t.fau' at line 1
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:336)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:347)
	at com.jfinal.plugin.activerecord.Db.find(Db.java:271)
	at com.ht.fault.order.ManageService.groupType(ManageService.java:270)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.CGLIB$groupType$13(<generated>)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d$$FastClassByCGLIB$$16354604.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:82)
	at com.jfinal.aop.Callback.intercept(Callback.java:96)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.groupType(<generated>)
	at com.ht.fault.order.ManageController.faultPie(ManageController.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.intercept(ExceptionIntoLogInterceptor.java:21)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.SSOInterceptor.intercept(SSOInterceptor.java:73)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.BaseInterceptor.intercept(BaseInterceptor.java:16)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values, f.`type` names  from ht_im_order_take t JOIN ht_im_fault_form f ON t.fau' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2683)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2144)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2310)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:321)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:334)
	... 47 more

2018-10-26 10:19:50
[ERROR]-[Thread: qtp1684792003-30]-[com.jfinal.core.ActionHandler.handle()]: /manage/faultPie
com.jfinal.render.RenderException: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:63)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:99)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.template.source.FileSource.getContent(FileSource.java:70)
	at com.jfinal.template.Engine.buildTemplateBySourceFactory(Engine.java:153)
	at com.jfinal.template.Engine.getTemplate(Engine.java:138)
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:60)
	... 26 more

2018-10-26 10:20:01
[INFO]-[Thread: main]-[org.eclipse.jetty.server.Server.doStart()]: jetty-8.1.8.v20121106

2018-10-26 10:20:01
[INFO]-[Thread: main]-[org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitServlet()]: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

2018-10-26 10:20:01
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:20:01
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:20:01
[WARN]-[Thread: main]-[net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded()]: diskStorePath 'C:\Users\ADMINI~1\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5028980364086955012diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.

2018-10-26 10:20:01
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5028980364086955012diskstore\token_time.data

2018-10-26 10:20:02
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5028980364086955012diskstore\token_user%0049d.data

2018-10-26 10:20:02
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5028980364086955012diskstore\user%0049d_token.data

2018-10-26 10:20:02
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-1} inited

2018-10-26 10:20:12
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-2} inited

2018-10-26 10:20:12
[INFO]-[Thread: main]-[org.eclipse.jetty.server.AbstractConnector.doStart()]: Started SelectChannelConnector@0.0.0.0:8082

2018-10-26 10:20:15
[INFO]-[Thread: qtp1684792003-31]-[com.xxl.sso.core.util.JedisUtil.getInstance()]: >>>>>>>>>>> xxl-sso, JedisUtil.ShardedJedisPool init success.

2018-10-26 10:20:16
[ERROR]-[Thread: qtp1684792003-30]-[com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.logWrite()]: 
---Exception Log Begin---
Controller:com.ht.fault.order.ManageController
Method:faultPie
Exception Type:com.jfinal.plugin.activerecord.ActiveRecordException
Exception Details:
com.jfinal.plugin.activerecord.ActiveRecordException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values, f.`type` names  from ht_im_order_take t JOIN ht_im_fault_form f ON t.fau' at line 1
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:336)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:347)
	at com.jfinal.plugin.activerecord.Db.find(Db.java:271)
	at com.ht.fault.order.ManageService.groupType(ManageService.java:270)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.CGLIB$groupType$13(<generated>)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d$$FastClassByCGLIB$$16354604.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:82)
	at com.jfinal.aop.Callback.intercept(Callback.java:96)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.groupType(<generated>)
	at com.ht.fault.order.ManageController.faultPie(ManageController.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.intercept(ExceptionIntoLogInterceptor.java:21)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.SSOInterceptor.intercept(SSOInterceptor.java:73)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.BaseInterceptor.intercept(BaseInterceptor.java:16)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values, f.`type` names  from ht_im_order_take t JOIN ht_im_fault_form f ON t.fau' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2683)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2144)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2310)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:321)
	at com.jfinal.plugin.activerecord.DbPro.find(DbPro.java:334)
	... 47 more

2018-10-26 10:20:16
[ERROR]-[Thread: qtp1684792003-30]-[com.jfinal.core.ActionHandler.handle()]: /manage/faultPie
com.jfinal.render.RenderException: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:63)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:99)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.template.source.FileSource.getContent(FileSource.java:70)
	at com.jfinal.template.Engine.buildTemplateBySourceFactory(Engine.java:153)
	at com.jfinal.template.Engine.getTemplate(Engine.java:138)
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:60)
	... 26 more

2018-10-26 10:21:33
[INFO]-[Thread: main]-[org.eclipse.jetty.server.Server.doStart()]: jetty-8.1.8.v20121106

2018-10-26 10:21:33
[INFO]-[Thread: main]-[org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitServlet()]: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

2018-10-26 10:21:33
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:21:33
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:21:33
[WARN]-[Thread: main]-[net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded()]: diskStorePath 'C:\Users\ADMINI~1\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created7575552297614105425diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.

2018-10-26 10:21:33
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created7575552297614105425diskstore\token_user%0049d.data

2018-10-26 10:21:33
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created7575552297614105425diskstore\user%0049d_token.data

2018-10-26 10:21:33
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created7575552297614105425diskstore\token_time.data

2018-10-26 10:21:33
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-1} inited

2018-10-26 10:21:48
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-2} inited

2018-10-26 10:21:48
[INFO]-[Thread: main]-[org.eclipse.jetty.server.AbstractConnector.doStart()]: Started SelectChannelConnector@0.0.0.0:8082

2018-10-26 10:21:56
[INFO]-[Thread: qtp1684792003-32]-[com.xxl.sso.core.util.JedisUtil.getInstance()]: >>>>>>>>>>> xxl-sso, JedisUtil.ShardedJedisPool init success.

2018-10-26 10:22:20
[INFO]-[Thread: main]-[org.eclipse.jetty.server.Server.doStart()]: jetty-8.1.8.v20121106

2018-10-26 10:22:20
[INFO]-[Thread: main]-[org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitServlet()]: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

2018-10-26 10:22:20
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:22:20
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:22:20
[WARN]-[Thread: main]-[net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded()]: diskStorePath 'C:\Users\ADMINI~1\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5863210292878323335diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.

2018-10-26 10:22:20
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5863210292878323335diskstore\user%0049d_token.data

2018-10-26 10:22:20
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5863210292878323335diskstore\token_user%0049d.data

2018-10-26 10:22:20
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5863210292878323335diskstore\token_time.data

2018-10-26 10:22:20
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-1} inited

2018-10-26 10:22:30
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-2} inited

2018-10-26 10:22:30
[INFO]-[Thread: main]-[org.eclipse.jetty.server.AbstractConnector.doStart()]: Started SelectChannelConnector@0.0.0.0:8082

2018-10-26 10:22:35
[INFO]-[Thread: qtp1684792003-27]-[com.xxl.sso.core.util.JedisUtil.getInstance()]: >>>>>>>>>>> xxl-sso, JedisUtil.ShardedJedisPool init success.

2018-10-26 10:23:06
[INFO]-[Thread: main]-[org.eclipse.jetty.server.Server.doStart()]: jetty-8.1.8.v20121106

2018-10-26 10:23:06
[INFO]-[Thread: main]-[org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitServlet()]: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

2018-10-26 10:23:06
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:23:06
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 10:23:06
[WARN]-[Thread: main]-[net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded()]: diskStorePath 'C:\Users\ADMINI~1\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created1980414450142303322diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.

2018-10-26 10:23:06
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created1980414450142303322diskstore\token_time.data

2018-10-26 10:23:06
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created1980414450142303322diskstore\token_user%0049d.data

2018-10-26 10:23:06
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created1980414450142303322diskstore\user%0049d_token.data

2018-10-26 10:23:07
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-1} inited

2018-10-26 10:23:19
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-2} inited

2018-10-26 10:23:19
[INFO]-[Thread: main]-[org.eclipse.jetty.server.AbstractConnector.doStart()]: Started SelectChannelConnector@0.0.0.0:8082

2018-10-26 10:23:22
[INFO]-[Thread: qtp1684792003-28]-[com.xxl.sso.core.util.JedisUtil.getInstance()]: >>>>>>>>>>> xxl-sso, JedisUtil.ShardedJedisPool init success.

2018-10-26 11:51:18
[INFO]-[Thread: main]-[org.eclipse.jetty.server.Server.doStart()]: jetty-8.1.8.v20121106

2018-10-26 11:51:18
[INFO]-[Thread: main]-[org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitServlet()]: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

2018-10-26 11:51:18
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 11:51:18
[INFO]-[Thread: main]-[org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized()]: started o.e.j.w.WebAppContext{/,file:/E:/GIT/fault/src/main/webapp/}

2018-10-26 11:51:18
[WARN]-[Thread: main]-[net.sf.ehcache.DiskStorePathManager.resolveAndLockIfNeeded()]: diskStorePath 'C:\Users\ADMINI~1\AppData\Local\Temp' is already used by an existing CacheManager either in the same VM or in a different process.
The diskStore path for this CacheManager will be set to C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5683350542075454626diskstore.
To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.

2018-10-26 11:51:18
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5683350542075454626diskstore\token_user%0049d.data

2018-10-26 11:51:18
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5683350542075454626diskstore\user%0049d_token.data

2018-10-26 11:51:18
[WARN]-[Thread: main]-[net.sf.ehcache.store.disk.DiskStorageFactory.<init>()]: Data in persistent disk stores is ignored for stores from automatically created directories.
Remove diskPersistent or resolve the conflicting disk paths in cache configuration.
Deleting data file C:\Users\ADMINI~1\AppData\Local\Temp\ehcache_auto_created5683350542075454626diskstore\token_time.data

2018-10-26 11:51:19
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-1} inited

2018-10-26 11:51:28
[INFO]-[Thread: main]-[com.alibaba.druid.pool.DruidDataSource.init()]: {dataSource-2} inited

2018-10-26 11:51:28
[INFO]-[Thread: main]-[org.eclipse.jetty.server.AbstractConnector.doStart()]: Started SelectChannelConnector@0.0.0.0:8082

2018-10-26 11:51:29
[INFO]-[Thread: qtp1684792003-28]-[com.xxl.sso.core.util.JedisUtil.getInstance()]: >>>>>>>>>>> xxl-sso, JedisUtil.ShardedJedisPool init success.

2018-10-26 11:51:29
[WARN]-[Thread: qtp1684792003-28]-[org.eclipse.jetty.http.HttpGenerator.addContent()]: Ignoring extra content {}

2018-10-26 15:04:17
[WARN]-[Thread: qtp1684792003-32]-[org.eclipse.jetty.http.HttpGenerator.addContent()]: Ignoring extra content {}

2018-10-26 15:04:19
[WARN]-[Thread: qtp1684792003-32]-[org.eclipse.jetty.http.HttpGenerator.addContent()]: Ignoring extra content {}

2018-10-26 15:04:20
[WARN]-[Thread: qtp1684792003-29]-[org.eclipse.jetty.http.HttpGenerator.addContent()]: Ignoring extra content {}

2018-10-26 15:04:36
[WARN]-[Thread: qtp1684792003-32]-[org.eclipse.jetty.http.HttpGenerator.addContent()]: Ignoring extra content {}

2018-10-26 15:11:48
[INFO]-[Thread: qtp1684792003-31]-[com.jfinal.kit.LogKit.info()]: (0:0:0:0:0:0:0:1)/manage/findAllStaff -- 返回数据:{"msg":"请求成功！","code":200,"data":[{"ADDRESS":"西安市灞桥区军大二院家属院11号楼110号","BIRTHDAY":"1979-12-09","CREATETIME":"2018-10-22 09:23:56","DEPARTID":null,"DINGUSERID":null,"EMAIL":null,"EMP_STATUS":"1","ENTRY_DATE":"2017-11-23","ID":"3aa072cde04a4c6ba385631a275d7f96","ID_CARD":"610425197912092011","IS_MARRIED":"1","NATION":"汉","NATIVE_PLACE":"陕西","PASSWORD":"e10adc3949ba59abbe56e057f20f883e","PHONE":"18681884918","PHOTO":null,"POLITICS":"党员","REALNAME":"张科学","ROLE":"5","SEX":"1","SOURCE":"0","STAFF_DEPT":"23","STAFF_DEPTNAME":"信息科","STAFF_ID":"15306726810433","STAFF_NO":"000005","STAFF_POST":"11","STAFF_POSTNAME":"科长","STATUS":1,"USERNAME":"18681884918","WORK_UNIT":"宝鸡高新人民医院","WORKING_DATE":"2002-07-01"},{"ADDRESS":"陕西省宝鸡市渭滨区姜谭路10号孔一区3251号","BIRTHDAY":"1992-06-27","CREATETIME":"2018-10-22 09:24:12","DEPARTID":null,"DINGUSERID":null,"EMAIL":null,"EMP_STATUS":"1","ENTRY_DATE":"2015-11-01","ID":"b442d68c2faa4568937ff316fc2c01c8","ID_CARD":"610302199206272516","IS_MARRIED":"0","NATION":"汉","NATIVE_PLACE":"山东","PASSWORD":"e10adc3949ba59abbe56e057f20f883e","PHONE":"18702936799","PHOTO":null,"POLITICS":"团员","REALNAME":"吴伟楠","ROLE":"5","SEX":"1","SOURCE":"0","STAFF_DEPT":"101","STAFF_DEPTNAME":"软件组","STAFF_ID":"15306738644441","STAFF_NO":"000572","STAFF_POST":"58","STAFF_POSTNAME":"初级运维工程师","STATUS":1,"USERNAME":"18702936799","WORK_UNIT":"兰州电机厂","WORKING_DATE":"2015-11-01"},{"ADDRESS":"陕西省宝鸡市金台区金台大道7号院4号楼1单元10号","BIRTHDAY":"1992-08-07","CREATETIME":"2018-10-22 09:24:12","DEPARTID":null,"DINGUSERID":null,"EMAIL":null,"EMP_STATUS":"1","ENTRY_DATE":"2015-12-09","ID":"7e4c7d428b4d43219f363ef494fee905","ID_CARD":"610302199208070037","IS_MARRIED":"1","NATION":"汉","NATIVE_PLACE":"江西","PASSWORD":"e10adc3949ba59abbe56e057f20f883e","PHONE":"15353340087","PHOTO":null,"POLITICS":"团员","REALNAME":"赵辰","ROLE":"5","SEX":"1","SOURCE":"0","STAFF_DEPT":"101","STAFF_DEPTNAME":"软件组","STAFF_ID":"15306738644447","STAFF_NO":"000579","STAFF_POST":"58","STAFF_POSTNAME":"初级运维工程师","STATUS":1,"USERNAME":"15353340087","WORK_UNIT":null,"WORKING_DATE":"2015-12-09"},{"ADDRESS":"陕西省宝鸡市金台区中山西路64号楼2单元25号","BIRTHDAY":"1989-08-31","CREATETIME":"2018-10-22 09:24:24","DEPARTID":null,"DINGUSERID":null,"EMAIL":null,"EMP_STATUS":"1","ENTRY_DATE":"2015-08-17","ID":"a2caf1da608c49978da8d214c2528054","ID_CARD":"610303198909010012","IS_MARRIED":"1","NATION":"汉","NATIVE_PLACE":"浙江","PASSWORD":"e10adc3949ba59abbe56e057f20f883e","PHONE":"18612237744","PHOTO":null,"POLITICS":"群众","REALNAME":"王融","ROLE":"5","SEX":"1","SOURCE":"0","STAFF_DEPT":"101","STAFF_DEPTNAME":"软件组","STAFF_ID":"15317035244104","STAFF_NO":"000555","STAFF_POST":"59","STAFF_POSTNAME":"软件工程师","STATUS":1,"USERNAME":"18612237744","WORK_UNIT":"东华软件股份公司","WORKING_DATE":"2012-08-01"},{"ADDRESS":"陕西省千阳县城关镇西大街9号","BIRTHDAY":"1987-11-02","CREATETIME":"2018-10-22 09:24:22","DEPARTID":null,"DINGUSERID":null,"EMAIL":null,"EMP_STATUS":"1","ENTRY_DATE":"2011-02-14","ID":"f04febfdb93b4759ab433d459bb67733","ID_CARD":"610328198711021813","IS_MARRIED":"1","NATION":"汉","NATIVE_PLACE":"陕西","PASSWORD":"e10adc3949ba59abbe56e057f20f883e","PHONE":"15129993024","PHOTO":null,"POLITICS":"群众","REALNAME":"师超","ROLE":"5","SEX":"1","SOURCE":"0","STAFF_DEPT":"106","STAFF_DEPTNAME":"硬件组","STAFF_ID":"15317035244060","STAFF_NO":"000003","STAFF_POST":"60","STAFF_POSTNAME":"中级运维工程师","STATUS":1,"USERNAME":"15129993024","WORK_UNIT":"陕西信合","WORKING_DATE":"2010-02-01"}]}

2018-10-26 16:15:36
[WARN]-[Thread: qtp1684792003-27]-[org.eclipse.jetty.http.HttpGenerator.addContent()]: Ignoring extra content {}

2018-10-26 16:15:37
[ERROR]-[Thread: qtp1684792003-32]-[com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.logWrite()]: 
---Exception Log Begin---
Controller:com.ht.fault.order.ManageController
Method:faultPie
Exception Type:java.lang.NumberFormatException
Exception Details:
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.ht.fault.order.ManageService.groupType(ManageService.java:266)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.CGLIB$groupType$12(<generated>)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d$$FastClassByCGLIB$$16354604.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:82)
	at com.jfinal.aop.Callback.intercept(Callback.java:96)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.groupType(<generated>)
	at com.ht.fault.order.ManageController.faultPie(ManageController.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.intercept(ExceptionIntoLogInterceptor.java:21)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.SSOInterceptor.intercept(SSOInterceptor.java:73)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.BaseInterceptor.intercept(BaseInterceptor.java:16)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)

2018-10-26 16:15:37
[ERROR]-[Thread: qtp1684792003-32]-[com.jfinal.core.ActionHandler.handle()]: /manage/faultPie
com.jfinal.render.RenderException: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:63)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:99)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.template.source.FileSource.getContent(FileSource.java:70)
	at com.jfinal.template.Engine.buildTemplateBySourceFactory(Engine.java:153)
	at com.jfinal.template.Engine.getTemplate(Engine.java:138)
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:60)
	... 26 more

2018-10-26 16:15:57
[ERROR]-[Thread: qtp1684792003-31]-[com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.logWrite()]: 
---Exception Log Begin---
Controller:com.ht.fault.order.ManageController
Method:faultPie
Exception Type:java.lang.NumberFormatException
Exception Details:
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.ht.fault.order.ManageService.groupType(ManageService.java:266)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.CGLIB$groupType$12(<generated>)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d$$FastClassByCGLIB$$16354604.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:82)
	at com.jfinal.aop.Callback.intercept(Callback.java:96)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.groupType(<generated>)
	at com.ht.fault.order.ManageController.faultPie(ManageController.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.intercept(ExceptionIntoLogInterceptor.java:21)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.SSOInterceptor.intercept(SSOInterceptor.java:73)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.BaseInterceptor.intercept(BaseInterceptor.java:16)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)

2018-10-26 16:15:57
[ERROR]-[Thread: qtp1684792003-31]-[com.jfinal.core.ActionHandler.handle()]: /manage/faultPie
com.jfinal.render.RenderException: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:63)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:99)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.template.source.FileSource.getContent(FileSource.java:70)
	at com.jfinal.template.Engine.buildTemplateBySourceFactory(Engine.java:153)
	at com.jfinal.template.Engine.getTemplate(Engine.java:138)
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:60)
	... 26 more

2018-10-26 16:16:55
[ERROR]-[Thread: qtp1684792003-27]-[com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.logWrite()]: 
---Exception Log Begin---
Controller:com.ht.fault.order.ManageController
Method:faultPie
Exception Type:java.lang.NumberFormatException
Exception Details:
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.ht.fault.order.ManageService.groupType(ManageService.java:266)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.CGLIB$groupType$12(<generated>)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d$$FastClassByCGLIB$$16354604.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:82)
	at com.jfinal.aop.Callback.intercept(Callback.java:96)
	at com.ht.fault.order.ManageService$$EnhancerByCGLIB$$c9349c8d.groupType(<generated>)
	at com.ht.fault.order.ManageController.faultPie(ManageController.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at com.ht.fault.common.interceptor.ExceptionIntoLogInterceptor.intercept(ExceptionIntoLogInterceptor.java:21)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.SSOInterceptor.intercept(SSOInterceptor.java:73)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.ht.fault.common.interceptor.BaseInterceptor.intercept(BaseInterceptor.java:16)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)

2018-10-26 16:16:55
[ERROR]-[Thread: qtp1684792003-27]-[com.jfinal.core.ActionHandler.handle()]: /manage/faultPie
com.jfinal.render.RenderException: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:63)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:99)
	at com.ht.fault.common.HtFaultServiceHandler.handle(HtFaultServiceHandler.java:23)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: File not found : E:\GIT\fault\src\main\webapp/manage/faultPie.html
	at com.jfinal.template.source.FileSource.getContent(FileSource.java:70)
	at com.jfinal.template.Engine.buildTemplateBySourceFactory(Engine.java:153)
	at com.jfinal.template.Engine.getTemplate(Engine.java:138)
	at com.jfinal.render.TemplateRender.render(TemplateRender.java:60)
	... 26 more
